version: "3.0"
services:
  # Backend
  node_backend:
    image: registry.s-01.wutthiphon.space/kmutnb-backend-iot-mobile-dev-project:c92b9c36c1bf9e883eb6ad9f15b4e2f39dfd2169
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "101:8000"
    networks:
      - network
    environment:
      - BACKEND_PORT
      - DATABASE_URL
      - SECRET_KEY
      - BCRYPT_ROUNDS
      - CRYPTO_IV
      - MQTT_HOST
      - MQTT_CLIENT_ID
      - MQTT_TOKEN
      - MQTT_SECERT

networks:
  network: