version: "3.0"
services:
  # Backend
  node_backend:
    image: registry.s-01.wutthiphon.space/kmutnb-backend-iot-mobile-dev-project:d84d2d08c40c6308242e7d375462452d70812bff
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "101:8000"
    networks:
      - network

networks:
  network: