version: "3.0"
services:
  # Backend
  node_backend:
    image: registry.s-01.wutthiphon.space/kmutnb-backend-iot-mobile-dev-project:9ce8439ad64e5adca8273e675d7b4e02154e7780
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "101:8000"
    networks:
      - network
    environment:
      - BACKEND_PORT
      - DATABASE_URL
      - SECRET_KEY
      - BCRYPT_ROUNDS
      - CRYPTO_IV
      - MQTT_HOST
      - MQTT_CLIENT_ID
      - MQTT_TOKEN
      - MQTT_SECERT

networks:
  network: